apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
      version: v1
  template:
    metadata:
      labels:
        app: httpd
        version: v1
      annotations:
        # Enable Istio sidecar injection
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: httpd
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Custom index.html for demo
        volumeMounts:
        - name: html-content
          mountPath: /usr/local/apache2/htdocs
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: html-content
        configMap:
          name: httpd-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kubernetes Sidecar Pattern Demo</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f0f8ff; }
            .container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            .header { color: #2c3e50; text-align: center; margin-bottom: 30px; }
            .info-box { background: #e8f4fd; padding: 15px; border-left: 4px solid #3498db; margin: 20px 0; }
            .highlight { color: #e74c3c; font-weight: bold; }
            .success { color: #27ae60; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚀 Kubernetes Sidecar Pattern Demo</h1>
                <h2>Apache HTTPD with Istio Service Mesh</h2>
            </div>
            
            <div class="info-box">
                <h3>📊 Pod Information</h3>
                <p><strong>Application:</strong> Apache HTTPD Server</p>
                <p><strong>Sidecar:</strong> Envoy Proxy (Istio)</p>
                <p><strong>Pattern:</strong> Sidecar Container Pattern</p>
            </div>
            
            <div class="info-box">
                <h3>🔄 Traffic Flow</h3>
                <p>1. <span class="highlight">External Request</span> → Istio Ingress Gateway</p>
                <p>2. <span class="highlight">Ingress Gateway</span> → Envoy Sidecar Proxy</p>
                <p>3. <span class="highlight">Envoy Proxy</span> → Apache HTTPD Container</p>
                <p>4. <span class="highlight">Response</span> ← Back through Envoy → Client</p>
            </div>
            
            <div class="info-box">
                <h3>✅ Sidecar Benefits Demonstrated</h3>
                <ul>
                    <li><span class="success">Traffic Management:</span> Load balancing, routing</li>
                    <li><span class="success">Security:</span> mTLS encryption between services</li>
                    <li><span class="success">Observability:</span> Metrics, tracing, logging</li>
                    <li><span class="success">Resilience:</span> Circuit breaking, retries</li>
                </ul>
            </div>
            
            <div class="info-box">
                <h3>🛠 Technical Details</h3>
                <p><strong>Hostname:</strong> <span id="hostname">Loading...</span></p>
                <p><strong>Timestamp:</strong> <span id="timestamp">Loading...</span></p>
                <p><strong>Request Headers:</strong> Check browser dev tools</p>
            </div>
            
            <div class="info-box">
                <h3>🔍 Verification Commands</h3>
                <pre style="background: #2c3e50; color: white; padding: 10px; border-radius: 5px;">
# Check pod containers (should show 2/2)
kubectl get pods -l app=httpd

# View Istio sidecar configuration
kubectl describe pod &lt;pod-name&gt;

# Check Envoy admin interface
kubectl port-forward &lt;pod-name&gt; 15000:15000
# Visit: http://localhost:15000

# View service mesh in Kiali
istioctl dashboard kiali
                </pre>
            </div>
        </div>
        
        <script>
            // Simple JavaScript to show dynamic content
            document.getElementById('hostname').textContent = window.location.hostname;
            document.getElementById('timestamp').textContent = new Date().toISOString();
        </script>
    </body>
    </html>
